---
- hosts: localhost
  connection: local
  remote_user: james
  gather_facts: yes
  vars_files:
    - vars/main.yml
  become: yes
  become_method: sudo
  tasks:
    - name: Install nodejs apt key
      apt_key:
        id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    - name: Add nodejs repo
      template:
        src: nodejs.j2
        dest: /etc/apt/sources.list.d/nodesource.list
    - name: Update cache and upgrade
      apt:
        update_cache: yes
        upgrade: "yes"
    - name: Install python packages
      pip:
        name: "{{ pip_packages }}"
    - name: Install base packages
      apt:
        name: "{{ basic_backages }}"
        state: latest
        update_cache: yes
    - name: Add the Gnome flatpak remote to the system installation
      flatpak_remote:
        name: gnome
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    - name: Install local packages
      apt:
        deb: "files/{{ item }}.deb"
      with_items:
      - "{{ local_packages }}"
    - name: Install Amazon Workspaces
      apt:
        deb: https://d3nt0h4h6pmmc4.cloudfront.net/workspacesclient_amd64.deb
    - name: Create group docker
      group:
        name: docker
        state: present
    - name: Adding user to groups
      user:
        name: "{{ ansible_user }}"
        groups: dialout, libvirt, kvm, docker
        append: yes
    - name: Install snap packages
      snap:
        name: "{{ snap_packages }}"
        state: present
    - name: Install typescript
      npm:
        name: typescript
        global: yes
    - name: Install classic snaps
      snap:
        name: "{{ snap_classics }}"
        state: present
        classic: yes