---
- hosts: local
  connection: local
  remote_user: james
  gather_facts: yes
  vars_files:
    - vars/main.yml
  become: yes
  become_method: sudo
  tasks:
    - name: Update cache and upgrade
      apt:
        update_cache: yes
        upgrade: "yes"
    - name: Install python packages
      pip:
        name: "{{ pip_packages }}"
    - name: Install base packages
      apt:
        name: "{{ basic_backages }}"
        state: latest
        update_cache: yes
    - name: Install PDF editor
      apt:
        deb: https://code-industry.net/public/master-pdf-editor-5.4.38-qt5-all.amd64.deb
    - name: Install lightworks
      apt:
        deb: files/Lightworks-2020.1-Beta-118883.deb
    - name: Adding user to groups
      user:
        name: "{{ ansible_user }}"
        groups: dialout, libvirt, kvm
        append: yes
    - name: Install snap packages
      snap:
        name: "{{ snap_packages }}"
        state: present
    - name: Install classic snaps
      snap:
        name: "{{ snap_classics }}"
        state: present
        classic: yes
    - name: Install gnome twitch
      flatpak:
        name: "{{ flatpak_packages }}"
        state: present
